name: in_app_review_kmp
description: "Plugin that allows to launch in-app and in-market review flows. Build over KMP"
version: 0.0.1
homepage: "https://github.com/SergeiMikhailovskii/kmp-app-review"

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.mikhailovskii.in_app_review
        pluginClass: InAppReviewPlugin
      ios:
        pluginClass: InAppReviewPlugin
