name: Publish new version
on:
  push:
    branches:
      - 'master'
jobs:
  create_tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Set version
        id: version
        run: |
          VERSION=$(git describe --tags `git rev-list --tags --max-count=1`)
          major=$(echo $VERSION | cut -d'.' -f1)
          minor=$(echo $VERSION | cut -d'.' -f2)
          fix=$(echo $VERSION | cut -d'.' -f3)
          echo "version=$major.$minor.$(($fix + 1))" >> $GITHUB_OUTPUT

      - name: Create tag
        uses: actions/github-script@v7.0.1
        with:
          github-token: ${{ secrets.API_KEY }}
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.version.outputs.version }}',
              sha: context.sha
            })
