name: Publish new version
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
jobs:
  build_project:
    permissions:
      id-token: write
    runs-on: macos-latest
    steps:
      - uses: dart-lang/setup-dart@v1.6.2
      - uses: subosito/flutter-action@v2.13.0

      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Set version
        id: version
        run: |
          VERSION=$(git describe --tags `git rev-list --tags --max-count=1` | cut -c 2-)
          major=$(echo $VERSION | cut -d'.' -f1)
          minor=$(echo $VERSION | cut -d'.' -f2)
          fix=$(echo $VERSION | cut -d'.' -f3)
          echo "version=$major.$minor.$fix" >> $GITHUB_OUTPUT

      - name: Update version
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'pubspec.yaml'
          propertyPath: 'version'
          value: ${{ steps.version.outputs.version }}
          commitChange: false

      - name: Install dependencies
        run: flutter pub get

      - name: Publish package
        run: dart pub publish --force